// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPDELPQLEVwU9Rji_Mxat5K47bXlXkKf8',
    appId: '1:1095262983676:web:62813517a44550bfd74e79',
    messagingSenderId: '1095262983676',
    projectId: 'midesi-65562',
    authDomain: 'midesi-65562.firebaseapp.com',
    storageBucket: 'midesi-65562.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUidEMNaB9nvhRazwnWn2Ifkk99LMhyQA',
    appId: '1:1095262983676:android:addd6a2b65c32eb0d74e79',
    messagingSenderId: '1095262983676',
    projectId: 'midesi-65562',
    storageBucket: 'midesi-65562.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs4SEyBw6AVfOtVYh09PywQxzHl5gR4rM',
    appId: '1:1095262983676:ios:3caaf7c941d76dcdd74e79',
    messagingSenderId: '1095262983676',
    projectId: 'midesi-65562',
    storageBucket: 'midesi-65562.firebasestorage.app',
    androidClientId: '1095262983676-v0n4gl06mg7vt8t6jcajk5d9m7rd50is.apps.googleusercontent.com',
    iosClientId: '1095262983676-lp4nc1ak4nktbbte1nih6a68sd6cij53.apps.googleusercontent.com',
    iosBundleId: 'com.example.desiShoppingSeller',
  );

}